In [3]:
import numpy as np 
a= np.arange(15).reshape(3,5)
arr1= np.array([[1,2,3,4,5],[3,4,5,6,7,],[9,8,7,6,5]])

print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype.name)
print(a.itemsize)
print(a.size)



(3, 5)
2
int32
4
15


In [5]:
a= np.array([20,30,40,50])
b= np.arange(4)
print(b)
print(a-b)
b**2
10*np.sin(a)
a<35

[0 1 2 3]
[20 29 38 47]


array([ True,  True, False, False])

In [53]:
#arange 
np.arange(0,2,0.3)


#operation rules  *= and +=
#dtype int로 강제되면 그런 일 생김
a= np.ones((2,3),dtype=int)
b=np.random.random((2,3))

a*=3
b+=a
print(b)
# a+=b
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

b= np.arange(12).reshape(3,-1)
print(b)
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.cumsum(axis=0))
print(b.cumsum(axis=1))

[[3.12281028 3.09580653 3.18705746]
 [3.09252743 3.47113108 3.05013877]]
[[0.30623346 0.90810374 0.80378006]
 [0.78947553 0.16545127 0.52879239]]
3.5018364561821484
0.16545126927934228
0.908103744505798
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [15]:
A= np.array([[1,1],[0,1]])
B= np.array([[2,0],[3,4]])
A * B
# 행렬곱
A.dot(B)
A@B

array([[5, 4],
       [3, 4]])

In [16]:
#Universal Func

B= np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))


42


In [35]:
#기울기
rx = np.array([np.random.randint(0,10,size=5)]).T
#X좌표
X = np.random.uniform(low=0, high=50,size=5)
print(rx)
print(X)
print(X*rx)

[[8]
 [3]
 [4]
 [3]
 [2]]
[31.69344748 26.70633849  4.44470128 11.77394296 13.16387117]
[[253.54757984 213.65070792  35.55761023  94.19154372 105.31096936]
 [ 95.08034244  80.11901547  13.33410384  35.32182889  39.49161351]
 [126.77378992 106.82535396  17.77880512  47.09577186  52.65548468]
 [ 95.08034244  80.11901547  13.33410384  35.32182889  39.49161351]
 [ 63.38689496  53.41267698   8.88940256  23.54788593  26.32774234]]


In [39]:
#Numpy DataTypes 
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )"""
import numpy as np
arr = np.array([1,2,3,4],dtype="c")

print(arr)

[b'1' b'2' b'3' b'4']


In [58]:
a= np.arange(10) **3
print(a)
print(a[:2])
print(a[2:5])
a[::2]=-100
print(a)
for i in a:
    print(i**(1/3))

[  0   1   8  27  64 125 216 343 512 729]
[0 1]
[ 8 27 64]
[-100    1 -100   27 -100  125 -100  343 -100  729]
nan
1.0
nan
3.0
nan
5.0
nan
6.999999999999999
nan
8.999999999999998


C:\Users\gijin100\AppData\Local\Temp\ipykernel_29672\2816885278.py:8: RuntimeWarning: invalid value encountered in power
  print(i**(1/3))


In [5]:
#shape Manipulatioon
import numpy as np
a = np.floor(10*np.random.random((3,4)))
print(a)
print(a.shape)
print(a.ravel())
A = a.reshape(6,2)
print(A.transpose(-1))

[[8. 4. 5. 7.]
 [0. 8. 2. 8.]
 [9. 4. 7. 1.]]
(3, 4)
[8. 4. 5. 7. 0. 8. 2. 8. 9. 4. 7. 1.]


ValueError: axes don't match array

In [9]:
a= np.floor(10*np.random.random((2,2,)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b,)))


[[5. 6.]
 [2. 0.]]
[[8. 7.]
 [3. 7.]]
[[5. 6.]
 [2. 0.]
 [8. 7.]
 [3. 7.]]
[[5. 6. 8. 7.]
 [2. 0. 3. 7.]]


In [2]:
from numpy import newaxis
np.column_stack((a,b,))
a= np.array([4,2])
b = np.array([3,8])
np.column_stack((a[:],b))
print(np.hstack((a,b)))
print(a[:newaxis])

NameError: name 'a' is not defined

In [30]:
#Splitting one array into several smaller ones
a2 =np.floor(10*np.random.random((2,12)))
print(a2)
#a2를 3개로 나눈다.
np.hsplit(a2,3)
#a2를 자르는데, 3번째까지로 한번 나누고, 4번재 포함.
k =np.hsplit(a2,(3,4,5))
for n in k:
    print(n)

[[8. 0. 6. 3. 7. 0. 0. 9. 7. 2. 5. 2.]
 [1. 3. 2. 1. 9. 1. 3. 9. 2. 2. 2. 3.]]
[[8. 0. 6.]
 [1. 3. 2.]]
[[3.]
 [1.]]
[[7.]
 [9.]]
[[0. 0. 9. 7. 2. 5. 2.]
 [1. 3. 9. 2. 2. 2. 3.]]


In [35]:
#simple copy  b=a로 하면 그냥 주소 복사한다.
a= np.arange(12)
b = a 
b is a
#얕은 복사

view_A = a.view()
view_A is a

slice_A = a[:]
slice_A is A
#깊은 복사

deep_A = a.copy()
deep_A is a

False

In [4]:
import numpy as np

a= np.floor(10 * np.random.random((2,12)))
print(a)

[[3. 1. 2. 4. 7. 2. 0. 9. 7. 7. 8. 7.]
 [5. 2. 9. 4. 1. 4. 3. 3. 0. 1. 1. 8.]]


In [38]:
#numpy indexing
a = np.arange(12)*2
i= np.array([1,2,3,6,7])
#괄호안에 i가 들어갈 수 있다.
print(a[i])
#shape는 j의 그것으로 reshape되어 출력된다.
j = np.array([[3,4],[9,7]])
a[j]


[ 2  4  6 12 14]


array([[ 6,  8],
       [18, 14]])

In [3]:
import numpy as np
#view,,copyreshape ,concat,concentrate 
#view는 오리진 어레이를 view해줄 뿐이지만, copy는 직접 값을 복사해온다.
#view는 원본이 바뀌면 같이 바뀌지만 copy는 그렇지 않다.
 
orgin_arr = np.array([1,2,3,4,5])
X_copy = orgin_arr.copy()
X_view = orgin_arr.view()
print(X_copy.base)
print(X_view.base)
orgin_arr[1]=42
X_view[3]=21
print(X_copy)
print(X_view)



None
[1 2 3 4 5]
[1 2 3 4 5]
[ 1 42  3 21  5]
